### ISSUE TITLE
Unable to get a list of video files

### ISSUE THREAD

**Issue by loanst** [vov4uk/Hik.Api#4]
Hello!
I tied to get a list of video files and download them using this api, but unsuccessfully. At the same time I can connect to cameras using "iVMS-4200 3.4.0.7 Client" desktop application, also I can connect by ip and I can list and download files using C# examples from Hikivision.

The output from console application. It displays no available channels:
![image](https://github.com/vov4uk/Hik.Api/assets/15771781/de73024e-7b5c-4149-ae96-2e6714db2e21)

The Hikivision demo application screen. 12 cameras and 3 recordings available:
![image](https://github.com/vov4uk/Hik.Api/assets/15771781/b3e2f34e-44ea-438a-b82a-ab02f1d5bbcc)

The screen from Hikivision configuration demo. 12 channels available:
![image](https://github.com/vov4uk/Hik.Api/assets/15771781/b373729c-dd88-4dca-84c1-82f0698fdef9)

One possible known problem: cameras recorder has wrong time configuration. Time on recorder is one hour less from current.
I commented this line to continue (it trowed an error, because the user don't have rights to change time):
![image](https://github.com/vov4uk/Hik.Api/assets/15771781/ad0113e2-f621-4547-ba13-17da7d0aa2e0)

Could you, please, check the code if it works and/or advise the solution?

**Comment by vov4uk** [comment]
Hi @loanst, please ping me in telegram @mr_vov4uk
